// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [{type: 'autogenerated', dirName: 'centro-de-ayuda'}],
};

module.exports = sidebars;
