from __future__ import annotations

import json
import re
import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]
DOCS_ROOT = REPO_ROOT / "docs"
HELP_CENTER_ROOT = DOCS_ROOT / "centro-de-ayuda"
MANIFEST_PATH = (
    REPO_ROOT / ".github" / "migrations" / "notion-public-docs-manifest.json"
)

CATEGORIES = (
    ("inicio-y-acceso", "Inicio y acceso", 1),
    (
        "perfil-de-empresa-en-google",
        "Conexión Perfil de Empresa en Google",
        2,
    ),
    ("visibilidad", "Visibilidad", 3),
    ("reputacion", "Reputación", 4),
    ("fidelizacion", "Fidelización", 5),
    ("beelma", "Beelma", 6),
    ("analitica", "Analítica", 7),
    ("cuenta-y-facturacion", "Cuenta y facturación", 8),
)


def frontmatter(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise AssertionError(f"Missing frontmatter in {path}")
    block = text.split("---\n", 2)[1]
    values: dict[str, str] = {}
    for line in block.splitlines():
        key, separator, value = line.partition(":")
        if separator:
            values[key.strip()] = value.strip().strip('"')
    return values


class PublicHelpCenterStructureTests(unittest.TestCase):
    def test_public_docs_are_home_plus_exact_notion_corpus(self) -> None:
        migrated = sorted(HELP_CENTER_ROOT.rglob("*.md"))
        public = sorted(DOCS_ROOT.rglob("*.md"))
        self.assertEqual(32, len(migrated))
        self.assertEqual(8, sum(path.name == "index.md" for path in migrated))
        self.assertEqual(24, sum(path.name != "index.md" for path in migrated))
        self.assertEqual(33, len(public))
        self.assertEqual(
            32,
            sum("notion_id" in frontmatter(path) for path in migrated),
        )

    def test_home_is_independent_and_links_every_category(self) -> None:
        home = DOCS_ROOT / "index.md"
        metadata = frontmatter(home)
        self.assertEqual("Centro de Ayuda Beesible", metadata["title"])
        self.assertEqual("1.0", metadata["version"])
        self.assertEqual("published", metadata["status"])
        self.assertEqual("Product", metadata["owner"])
        self.assertEqual("2026-09-09", metadata["last_reviewed"])
        self.assertEqual("/", metadata["slug"])
        self.assertNotIn("notion_id", metadata)

        targets = re.findall(r"\[[^]]+]\(([^)]+)\)", home.read_text(encoding="utf-8"))
        self.assertEqual(
            {
                f"centro-de-ayuda/{folder}/index.md"
                for folder, _, _ in CATEGORIES
            },
            set(targets),
        )
        self.assertTrue(all((DOCS_ROOT / target).is_file() for target in targets))

    def test_docs_contain_exactly_one_root_slug(self) -> None:
        root_slugs = [
            path
            for path in DOCS_ROOT.rglob("*.md")
            if frontmatter(path).get("slug") == "/"
        ]
        self.assertEqual([DOCS_ROOT / "index.md"], root_slugs)

    def test_internal_project_doc_is_outside_public_docs(self) -> None:
        flow = REPO_ROOT / "project-docs" / "flujo-agente-documentacion.md"
        self.assertTrue(flow.is_file())
        self.assertFalse((DOCS_ROOT / "flujo-agente-documentacion.md").exists())
        self.assertNotIn("slug", frontmatter(flow))
        self.assertIn("```mermaid\nflowchart TD", flow.read_text(encoding="utf-8"))

        readme = (REPO_ROOT / "project-docs" / "README.md").read_text(
            encoding="utf-8"
        )
        self.assertIn("no se publica en GitHub Pages", readme)
        self.assertIn("repositorio público", readme)
        self.assertIn("repositorio o sistema privado", readme)

    def test_fictitious_poc_content_and_snapshot_are_absent(self) -> None:
        self.assertFalse((DOCS_ROOT / "archivos-adjuntos.md").exists())
        self.assertFalse((DOCS_ROOT / "invitaciones.md").exists())
        self.assertFalse((DOCS_ROOT / "production-snapshots").exists())

        generator = (
            REPO_ROOT
            / ".github"
            / "scripts"
            / "generate-documentation-proposal.py"
        ).read_text(encoding="utf-8")
        generator_tests = (
            REPO_ROOT
            / ".github"
            / "scripts"
            / "tests"
            / "test_generate_documentation_proposal.py"
        ).read_text(encoding="utf-8")
        self.assertIn("production-snapshots", generator)
        self.assertIn("TemporaryDirectory", generator_tests)
        self.assertIn("production-snapshots", generator_tests)

    def test_sidebar_uses_category_indices_without_technical_parent(self) -> None:
        sidebar = (REPO_ROOT / "sidebars.js").read_text(encoding="utf-8")
        self.assertIn("type: 'autogenerated'", sidebar)
        self.assertIn("dirName: 'centro-de-ayuda'", sidebar)
        self.assertNotIn("dirName: '.'", sidebar)

        observed = []
        for folder, title, position in CATEGORIES:
            metadata = frontmatter(HELP_CENTER_ROOT / folder / "index.md")
            observed.append((metadata["title"], int(metadata["sidebar_position"])))
        self.assertEqual(
            [(title, position) for _, title, position in CATEGORIES],
            observed,
        )

    def test_site_identity_is_public_help_center(self) -> None:
        config = (REPO_ROOT / "docusaurus.config.js").read_text(encoding="utf-8")
        self.assertGreaterEqual(config.count("Centro de Ayuda Beesible"), 2)
        self.assertIn("sidebarPath: './sidebars.js'", config)
        self.assertNotIn("require.resolve('./sidebars.js')", config)
        self.assertNotIn("Documentación BeeDigital", config)
        self.assertNotIn("label: 'Documentación'", config)
        self.assertNotIn("project-docs", config)

    def test_all_migrated_internal_links_resolve_without_uuids(self) -> None:
        uuid = re.compile(r"[0-9a-f]{32}", re.IGNORECASE)
        broken: list[str] = []
        for source in HELP_CENTER_ROOT.rglob("*.md"):
            text = source.read_text(encoding="utf-8")
            for target in re.findall(r"!?\[[^]]*]\(([^)]+)\)", text):
                if re.match(r"^(?:https?|mailto|tel):|^#", target, re.IGNORECASE):
                    continue
                path = target.split("#", 1)[0]
                if uuid.search(target) or not (source.parent / path).is_file():
                    broken.append(f"{source.relative_to(REPO_ROOT)} -> {target}")
        self.assertEqual([], broken)

    def test_manifest_represents_only_notion_pages(self) -> None:
        manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
        self.assertEqual(32, manifest["source"]["markdown_pages"])
        paths = [
            item["path"]
            for category in manifest["categories"]
            for item in [category, *category["articles"]]
        ]
        self.assertEqual(32, len(paths))
        self.assertNotIn("docs/index.md", paths)


if __name__ == "__main__":
    unittest.main()
